Feature/ag grid for tables
lesiadmytrus/university-app pull request #28
Opened 2019-09-23 13:22 UTC by lesiadmytrus

Added ag-Grid for table

2019-09-23 13:29 UTC, vlodkopits requested changes

2019-09-23 13:29 UTC, vlodkopits commented on src/app/components/student/student.component.ts
> +  columnDefs = [
can you set Headers in the same way as a Students?
create const for table Headers to use it in ag-grid.

2019-09-23 15:46 UTC, dmutrokot requested changes

2019-09-23 15:46 UTC, dmutrokot commented on src/app/components/student/student.component.html
> +    style="width: 100%; height: 500px;"
It's kinda not so good way to write styles :)

2019-09-24 10:25 UTC, dmutrokot approved these changes

2019-09-24 10:26 UTC, vlodkopits requested changes

2019-09-24 10:27 UTC, vlodkopits approved these changes

2019-09-24 10:33 UTC, merged